In [1]:
pip install --upgrade -r "requirements.txt"

Requirement already satisfied: pandas in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: htrc-feature-reader in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 2)) (2.0.7)
Requirement already satisfied: wordcloud in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 3)) (1.9.6)
Requirement already satisfied: matplotlib in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 4)) (3.10.8)
Requirement already satisfied: keybert in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: gensim in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from -r requirements.txt (line 6)) (4.4.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: six in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from htrc-feature-reader->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: requests in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from htrc-feature-reader->-r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: python-rapidjson in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from htrc-feature-reader->-r requirements.txt (line 2)) (1.23)
Requirement already satisfied: pymarc in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from htrc-feature-reader->-r requirements.txt (line 2)) (5.3.1)
Requirement already satisfied: pillow in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from wordcloud->-r requirements.txt (line 3)) (11.1.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: pyparsing>=3 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: rich>=10.4.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from keybert->-r requirements.txt (line 5)) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from keybert->-r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from keybert->-r requirements.txt (line 5)) (5.3.0)
Requirement already satisfied: scipy>=1.7.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from gensim->-r requirements.txt (line 6)) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from gensim->-r requirements.txt (line 6)) (7.5.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from rich>=10.4.0->keybert->-r requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from rich>=10.4.0->keybert->-r requirements.txt (line 5)) (2.19.1)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from rich>=10.4.0->keybert->-r requirements.txt (line 5)) (4.12.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert->-r requirements.txt (line 5)) (0.1.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=0.22.2->keybert->-r requirements.txt (line 5)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=0.22.2->keybert->-r requirements.txt (line 5)) (3.5.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (5.3.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (2.11.0)
Requirement already satisfied: tqdm in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (4.67.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.22.2)
Requirement already satisfied: typer in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.28.1)
Requirement already satisfied: anyio in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (4.9.0)
Requirement already satisfied: certifi in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (2025.6.15)
Requirement already satisfied: httpcore==1.* in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.0.2)
Requirement already satisfied: idna in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: wrapt in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from smart_open>=1.8.1->gensim->-r requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: setuptools<82 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: colorama in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from tqdm->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.4.6)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from requests->htrc-feature-reader->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from requests->htrc-feature-reader->-r requirements.txt (line 2)) (2.3.0)
Requirement already satisfied: click>=8.2.1 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\haasi\miniconda3\envs\myenv\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert->-r requirements.txt (line 5)) (0.0.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import http.client
import json
import bz2
import re
import requests

import pandas as pd

from collections import defaultdict
# from sentence_transformers import SentenceTransformer
# from keybert import KeyBERT
# topicexplorer import workset.tez
from gensim import corpora, models

import numpy as np

import string
from collections import Counter
from htrc_features import Volume
from htrc_features.resolvers import HttpResolver
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [3]:
# key_word_model = KeyBERT('distilbert-base-nli-mean-tokens')

Get stop words

In [4]:
stop_en = requests.get('https://data.analytics.hathitrust.org/data/text/default_stopwords_en.txt')
stop_en = stop_en.text
stop_en = stop_en.split()

Functions to get volume data

In [5]:
def retrieve_data(volume_id):
    # """Retrieve page-level JSON data for a volume."""

    # conn.request("GET", f"/ef-api/volumes/{volume_id}", headers=headers)
    # res = conn.getresponse()

    # if res.status != 200:
    #     print(f"API request failed: {res.status} {res.reason}")
    #     return "ERROR"

    # raw = res.read()

    res = requests.get("https://data.htrc.illinois.edu/ef-api/volumes/" + volume_id)
    raw = res.content

    if (res.status_code == 200):
        try:
            parsed = json.loads(raw.decode("utf-8"))
            return parsed
        except Exception as e:
            # print("Failed to parse JSON response")
            return "ERROR"
    else:
        return "NOT FOUND"


def tokens_count(record):
    ''' Create the list of words per page and how many time the word is mentioned '''

    word_key_count = Counter()
    
    for page in record['data']['features']['pages']:
        if page['body']:
            for token, pos_count in page['body']['tokenPosCount'].items():
                word_key_count[token] += sum(pos_count.values())
                    
    return word_key_count

def get_keywords(text):

    # extract tokens only
    dictionary = corpora.Dictionary([text.keys()])

    # Step 2: convert dict → BoW format
    bow = [(dictionary.token2id[word], count) for word, count in text.items()]

    # Step 3: corpus must be a list of documents
    corpus = [bow]

    # Step 4: run LDA
    lda_model = models.LdaModel(corpus=corpus, id2word=dictionary, num_topics=5)
    
    topics = ()
    for topic in lda_model.print_topics(num_topics=40, num_words=10):
        topics += topic

    return topics

In [6]:
def clean_df(data, stop_en):
    df = pd.DataFrame({'count': data})
    df = df.reset_index()
    df = df.rename(columns={'index': 'word'})
    # df = df.sort_values(by='count', ascending=False)
    df = df[~df['word'].isin(stop_en)]
    df = df[~df['word'].isin(stop.title() for stop in stop_en)]
    df = df[~df['word'].isin(list(string.punctuation))]
    df = df[~df['word'].isin(["'s","''","-RRB-","-LRB-","``","--","p."])]
    return df

Get workset volumes

In [26]:
import requests
workset = requests.get("https://worksets.hathitrust.org/ef-api/worksets/1abe5340-28d2-11f1-806f-2d821d8659ab")

workset_content = workset.content
# raw = json.loads(workset_content)

# print(workset_content)

In [27]:
workset_json=workset.json()
workset_json['data']['htids']

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [8]:
data = raw['gathers']
print(data)

readable_json = json.dumps(data, indent=4) # Indent with 4 spaces

x = readable_json.split()
y = "http://hdl.handle.net/2027/"
volumes = []
for i in x:
    if y in i:
        z = i.replace(y,"")
        z = z.replace('"',"")
        volumes.append(z)

[{'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25m62k2k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sb3x99d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qv3cg1q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2zc7s61z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27w67j0m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20c4sx21'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2nz8124z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2j67981m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2k64b51v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2251fx5r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cf9jj9k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20863h80'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24x54v0f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rr1q00m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2z892s80'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2k06xc6p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m03z88w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26q1sv5r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21g0j64h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2n873b62'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dr2pm8d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2571808n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vt1h233'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m902f6c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cr5nq85'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2474739w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2639kh63'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2st7f843'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2q23rb9d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2k931j5n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2wm14572'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2h98zr49'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2p26qg08'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h28w38d9r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25d8ns5f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ww77b7k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2jm23t40'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dv1d108'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20p0x32h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2r49gn1j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2hm52x38'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2862bq00'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23f4m07w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2q52fr2b'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gq6rd7v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27659t0r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xp6vf96'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2p84474b'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2kh0fb0f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h29z90q3v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h22r3p829'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pk07d3x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qf8jx1c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2b853w18'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sb3x98x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d21rw72'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2f18ss68'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25h7c57p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2mk65m4x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2794161h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24j0b88g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2w37m71z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2b27q36h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xw4877t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2v40kb2r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2kk94q55'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23x83z06'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vd6ph28'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rn30k7n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2h41jz92'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2z60cd6q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pn8xs88'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2g44j297'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2bc3t853'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2np1ww54'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d795p2p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2f47h590'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21z42515'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27h1dz9q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20000b9z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2w669m5r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2mp4w06s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2n873b1n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cr5nq5q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dr2pm4g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2901zt14'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2736md4c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2tt4g499'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20k26p44'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m902f2f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dn4071j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rx93r2r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fn1141s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2st7f81n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m61c20m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26w96m79'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cn6zb0f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20c4sw9z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2c53fc54'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2zw1942n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d21rw4m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20v89v2p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dz03d04'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25d8ns1h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fx7490t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xw4873w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2w08wt6n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gq6rd4d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2s756x1n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2862bp6f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h29z90p99'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xs5jv1n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23f4m04f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2q81542m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qn5zp6j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26q1sv1t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2h708b8v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23x83x74'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2x63bh31'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2j09wg4g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pr7n56k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25q4rz03'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27h1dz5s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2v980368'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20z7178v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ms3kc8m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h29882z9f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2x34n384'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ks6jg5x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h22v2cn44'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2280594j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2p26qf76'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fq9qh83'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777661'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h29z90q4b'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777679'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2h98zr0c'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777646'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2416t999'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777653'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h28s4k130'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777703'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2wm14534'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2tm72c3n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fb4wz1x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vm4383w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gb1xt9k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h28p5vn08'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2wd3qc7g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2251fx29'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2nv99n85'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cz32h59'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2862bq1g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2nc5sq90'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2hq3s992'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777513'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vx06f7w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2r49gn3h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24f1mw7q'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777547'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20p0x330'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777554'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2bz61m52'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777521'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27659t17'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777539'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2mg7g73k'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777588'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gq6rd9t'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777596'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2q81546j'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777562'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2kh0fb2d'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777570'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23f4m08c'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777620'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2tx35j84'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777638'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sb3xb0h'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777604'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ht2gq20'}, {'id': 'http://hdl.handle.net/2027/uiug.30112109777612'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2js9hm16'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25h7c59n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gt5ft18'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23n20s2n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h28912346'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rb6wd95'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26d5pp7n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2t43jf4g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2v40kb37'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ft8dx2h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21n7z026'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2s46hj47'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2jm23t6z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2959cm0p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cc0v56t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2057d484'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2154f17w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2mw28s40'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2td9nm3h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2f766k3d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2kw57w57'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26q1sv67'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rf5kt23'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2c824s4z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sf2mq1v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d795p4n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2b853w2r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2z02zm9k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20000c1j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ks6jh0z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2tq5rs04'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fj29r1h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gf0n799'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2377669n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dj58v2r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2513v74k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2280599z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sq8qv9s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26t0h770'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2tm72c82'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20863h9g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m32nn8r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xd0r918'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2j38kw1b'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2k35ms03'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25t3gb87'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2125qn26'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rn30k65'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sn01g4f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2db7w251'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qn5zp8h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2bc3t834'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cc0v53c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27m04b8h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2x63bh50'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2hx16296'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2z60cd57'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2f47h571'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gx4561j'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23r0q54h'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24q7r246'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rf5ks91'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gf0n76v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pz51z4s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2445hq46'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vq2sn98'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sq8qv7t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h28s4k15z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ff3mb54'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2xg9fp22'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27s7j45q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2vh5cw1n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21834d87'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2n01054k'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fb4wz4c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h25t3gb5s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gb1xv15'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pv6bk00'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2930p64v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ws8hz1d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2p84472c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dr2pm6f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20k26p5m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2m902f4d'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2s17t46w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24b2xh0g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h29w09990'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h22b8vq00'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23b5wk94'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fn1143r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rx93r4q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cn6zb1x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sx64n3g'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dn40721'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fx7492s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h22n4zv9z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27d2qk3z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qf8jw89'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21n7xz9q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ng4h40c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2t727t1w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2dz03d1m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2mg7g704'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27659s85'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2cz32h1c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2w08wt8m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2697090s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2t14v17m'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2v11vx8x'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fq9qh45'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h24q7r23q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2rj4963v'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2ns0m90f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d795p0q'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2qj7891n'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2b853v9p'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2c824s01'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h23t9dj4t'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2f18ss49'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h21v5br5c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h26m33f9r'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2pk07d1z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h20v89v35'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2gx45602'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2nk36h26'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2d50g85c'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2sn01g3z'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2j38kv88'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2fb4wz3w'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2251fx3s'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h2h708c0f'}, {'id': 'http://hdl.handle.net/2027/ucbk.ark:/28722/h27p8tr3g'}, {'id': 'htt

Handle Volume

In [17]:
worked = 0
failed = 0
noget = 0
for vol in volumes:
    # print("https://data.htrc.illinois.edu/ef-api/volumes/" + vol)
    # res = requests.get("https://data.htrc.illinois.edu/ef-api/volumes/" + vol)
    # raw = res.content

    # if (res.status_code == 200):
    #     try:
    #         parsed = json.loads(raw.decode("utf-8"))
    #         print('worked')
    #         worked += 1
    #     except Exception as e:
    #         failed += 1
    #         print(e)
    # else: 
    #     noget += 1

    data = retrieve_data(vol)
    print(data)

    if (data == "NOT FOUND"): 
        notget += 1
    elif (data == "ERROR"):
        failed += 1
    else: 
        worked += 1

print ("WORKED: " + str(worked))
print ("FAILED: " + str(failed))
print ("NOT GOT: " + str(failed))

NOT FOUND

NameError: name 'notget' is not defined

Testing with just two working volumes

In [10]:
parsed1 = retrieve_data('uiug.30112104141319')
parsed2 = retrieve_data('uiug.30112104141103')
print(parsed1)
print(parsed2)

{'code': 200, 'data': {'@context': 'https://worksets.htrc.illinois.edu/context/ef_context.jsonld', 'schemaVersion': 'https://schemas.hathitrust.org/EF_Schema_v_3.0', 'id': 'https://data.analytics.hathitrust.org/extracted-features/20200210/uiug.30112104141319', 'htid': 'uiug.30112104141319', 'type': 'DataFeed', 'publisher': {'id': 'https://analytics.hathitrust.org', 'type': 'Organization', 'name': 'HathiTrust Research Center'}, 'datePublished': 20200210, 'metadata': {'schemaVersion': 'https://schemas.hathitrust.org/EF_Schema_MetadataSubSchema_v_3.0', 'id': 'http://hdl.handle.net/2027/uiug.30112104141319', 'type': ['DataFeedItem', 'PublicationVolume'], 'dateCreated': 20200209, 'title': 'Corpsman.', 'contributor': {'id': 'http://www.viaf.org/viaf/152739208', 'type': 'http://id.loc.gov/ontologies/bibframe/Organization', 'name': 'Job Corps (U.S.)'}, 'pubDate': 1967, 'publisher': {'id': 'http://catalogdata.library.illinois.edu/lod/entities/ProvisionActivityAgent/ht/Job%20Corps', 'type': 'http://id.loc.gov/ontologies/bibframe/Organization', 'name': 'Job Corps'}, 'pubPlace': {'id': 'http://id.loc.gov/vocabulary/countries/dcu', 'type': 'http://id.loc.gov/ontologies/bibframe/Place', 'name': 'District of Columbia'}, 'language': 'eng', 'accessRights': 'pd', 'accessProfile': 'google', 'sourceInstitution': {'type': 'http://id.loc.gov/ontologies/bibframe/Organization', 'name': 'UIUC'}, 'mainEntityOfPage': ['https://catalog.hathitrust.org/Record/000526435', 'http://catalog.hathitrust.org/api/volumes/brief/oclc/2253770.json', 'http://catalog.hathitrust.org/api/volumes/full/oclc/2253770.json'], 'lccn': '2004238714', 'oclc': '2253770', 'issn': '0010-9002', 'genre': ['http://id.loc.gov/vocabulary/marcgt/doc', 'http://id.loc.gov/vocabulary/marcgt/gov'], 'enumerationChronology': 'v.3:22 (Nov 1967)', 'typeOfResource': 'http://id.loc.gov/ontologies/bibframe/Text', 'lastRightsUpdateDate': 20180307, 'isPartOf': {'id': 'http://www.worldcat.org/oclc/2253770', 'type': 'CreativeWorkSeries', 'journalTitle': 'Corpsman (Washington, D.C.)'}}, 'features': {'schemaVersion': 'https://schemas.hathitrust.org/EF_Schema_FeaturesSubSchema_v_3.0', 'id': 'http://hdl.handle.net/2027/uiug.30112104141319', 'type': 'DataFeedItem', 'dateCreated': 20200124, 'pageCount': 8, 'pages': [{'seq': '00000001', 'version': '50cc2b91b7d4b923acdc1003a048f958', 'tokenCount': 1103, 'lineCount': 191, 'emptyLineCount': 7, 'sentenceCount': 62, 'header': None, 'body': {'tokenCount': 1103, 'lineCount': 191, 'emptyLineCount': 7, 'sentenceCount': 62, 'capAlphaSeq': 4, 'beginCharCount': {'e': 2, 's': 9, 'n': 6, 'N': 6, 'T': 15, 't': 11, 'J': 3, 'u': 1, 'f': 8, 'F': 2, 'A': 4, 'a': 7, 'm': 3, 'M': 4, 'i': 11, '"': 5, '1': 1, 'V': 1, 'q': 1, 'L': 4, "'": 1, 'b': 6, 'g': 3, 'B': 4, 'l': 2, 'P': 2, 'p': 2, 'C': 9, 'H': 1, 'c': 2, 'W': 8, 'h': 8, '(': 2, 'r': 4, 'w': 8, 'R': 1, '3': 1, 'k': 1, '^': 1, 'D': 2, '>': 1, 'o': 4, 'S': 2, 'd': 5}, 'endCharCount': {'E': 1, 'e': 29, 's': 11, 'n': 9, '.': 26, '9': 1, 'y': 7, 't': 10, 'f': 5, '&': 1, 'A': 1, 'a': 3, 'm': 2, ')': 3, '"': 4, '-': 16, ',': 3, 'g': 4, 'l': 4, 'p': 1, '2': 1, 'h': 6, '7': 1, 'r': 6, 'w': 2, 'k': 3, '>': 1, 'o': 4, 'S': 2, 'd': 17}, 'tokenPosCount': {'joining': {'VBG': 1}, 'IN': {'IN': 1}, 'Flags': {'NNS': 1}, 'Brothers': {'NN': 1, 'NNPS': 1}, 'One': {'CD': 1}, 'trouble': {'NN': 1}, 'read': {'VB': 1, 'VBD': 1}, 'Falls': {'NNP': 3}, 'headline': {'NN': 1}, 'for': {'IN': 11}, 'Lewiston': {'NNP': 1}, 'Samuelson': {'NNP': 1}, '``': {'``': 9}, 'dot': {'NN': 1}, 'Winners': {'NNS': 2}, 'find': {'VB': 1}, 'school': {'NN': 1}, 'knowing': {'VBG': 1}, 'duty': {'NN': 1}, 'choking': {'VBG': 1}, 'officer': {'NN': 1}, 'relative': {'JJ': 1}, 'feel': {'VB': 1}, 'working': {'VBG': 1}, 'people': {'NNS': 2}, 'newspaper': {'NN': 1}, 'visits': {'NNS': 1}, 'recognized': {'VBD': 1}, 'years': {'NNS': 6}, 'Department': {'NNP': 1}, 'For': {'IN': 1}, 'tells': {'VBZ': 1}, 'count': {'VBP': 1}, 'door': {'NN': 1}, 'bus': {'NN': 1}, 'in': {'IN': 17}, 'MURPH-Harold': {'JJ': 1}, 'With': {'IN': 1}, 'professional': {'JJ': 1}, 'dream': {'NN': 1}, 'Harold': {'NNP': 1}, 'have': {'VB': 1, 'VBP': 4}, 'needed': {'VBD': 1}, 'your': {'PRP$': 1}, 'John': {'NNP': 1}, 'feeling': {'NN': 1}, 'California': {'NNP': 3}, 'are': {'VBP': 2}, 'is': {'VBZ': 7}, 'his': {'PRP$': 9}, 'Trail': {'NN': 1}, 'too': {'RB': 1}, 'graduate': {'NN': 1}, 'Rico': {'NNP': 1}, 'built': {'VBN': 2}, 'stayed': {'VBD': 1}, 'artificial': {'JJ': 1}, 'seen': {'VBN': 2}, 'said': {'VBD': 1}, '135': {'CD': 1}, 'All': {'DT': 1}, 'TRAIL-Kenneth': {'NNP': 1}, 'soon': {'RB': 1}, 'JOB': {'NN': 1}, 'nobody': {'NN': 1}, 'got': {'VBD': 1}, 'all-the': {'JJ': 1}, 'worse': {'JJR': 1}, 'watching': {'VBG': 1}, 'Washington': {'NNP': 1}, 'They': {'PRP': 3}, 'shook': {'VBD': 1}, 'lifesaving': {'JJ': 1, 'NN': 2}, 'system': {'NN': 1}, 'hands': {'NNS': 1}, 'weekend': {'NN': 1}, 'signs': {'NNS': 2}, 'history': {'NN': 1}, 'three': {'CD': 1}, 'walked': {'VBD': 1}, 'smooth': {'JJ': 1}, 'meeting': {'NN': 1}, 'join': {'VB': 2}, 'thought': {'VBN': 1}, 'fir': {'NN': 1}, '.': {'.': 60}, 'In': {'IN': 2}, 'but': {'CC': 2}, 'state': {'NN': 1}, 'nation': {'NN': 1}, 'HE': {'PRP': 1}, 'future': {'JJ': 1}, 'President': {'NNP': 1}, 'Corpsman': {'NN': 1, 'NNP': 5}, 'Build': {'NNP': 1}, 'dots': {'NNS': 1}, 'career': {'NN': 1}, 'what': {'WDT': 1}, 'would': {'MD': 2}, 'relatives': {'NNS': 1}, 'students': {'NNS': 1}, 'THE': {'DT': 2}, 'center': {'NN': 3}, 'annual': {'JJ': 1}, 'running': {'VBG': 1}, 'glad': {'JJ': 1}, 'flew': {'VBD': 1}, 'own': {'JJ': 1}, 'up': {'RP': 2}, 'so': {'IN': 1}, 'Walker': {'NNP': 1}, 'Secretary': {'NNP': 1}, 'Headquarters': {'NN': 1}, 'Walton': {'NNP': 1}, '22': {'CD': 1}, 'minute': {'NN': 1}, 'all': {'PDT': 1, 'DT': 1}, 'him': {'PRP': 1}, 'dropout': {'NN': 1}, 'asthma': {'NN': 1}, 'trails': {'VBZ': 1}, '<': {'JJR': 1}, 'served': {'VBN': 1}, 'swallowed': {'VBD': 1}, 'thanks': {'NNS': 1}, 'alert': {'JJ': 1}, 'Duty': {'NN': 1}, 'resuscitation': {'NN': 1}, 'had': {'VBD': 5}, 'miles': {'NNS': 1}, '2-NEWMAN': {'NN': 1}, 'trail': {'NN': 5}, 'tropical': {'JJ': 1}, 'onto': {'IN': 1}, 'birth': {'NN': 1}, 'announced': {'VBN': 1}, 'Leon': {'NNP': 9}, 'cut': {'VBN': 1, 'VBD': 1}, 'patterns': {'NNS': 1}, 'page': {'NN': 2}, 'every': {'DT': 1}, 'NAVAL': {'JJ': 1, 'NNP': 1}, 'came': {'VBD': 1}, 'idea': {'NN': 1}, 'before': {'IN': 1}, 'traveled': {'VBD': 1}, '&': {'CC': 1}, 'Be': {'VB': 1}, 'trees': {'NNS': 1}, 'just': {'RB': 1}, 'hearing': {'NN': 1}, 'Nation': {'NNP': 1}, 'left': {'VBN': 2}, 'recruiting': {'VBG': 1}, 'it': {'PRP': 2}, 'crowd': {'NN': 2}, 'brothers': {'NNS': 3}, 'School': {'NNP': 1}, 'ca': {'MD': 1}, 'two': {'CD': 6}, 'A': {'DT': 1}, 'failed': {'VBD': 1}, 'tests': {'NNS': 2}, 'a': {'DT': 17}, 'And': {'CC': 1}, 'spruce': {'VB': 1}, 'applied': {'VBD': 1}, 'movie': {'NN': 1}, 'passed': {'VBD': 1}, 'job': {'NN': 1}, 'Corpsmen': {'NNP': 12}, 'sworn': {'VBN': 2}, 'White': {'NNP': 1}, 'became': {'VBD': 1}, 'walk': {'NN': 3}, 'Johnson': {'NNP': 1}, 'as': {'IN': 2}, 'Saved': {'VBD': 1}, 'build': {'VB': 1}, 'stomach': {'NN': 1}, 'trail-called': {'JJ': 1}, 'Buddies': {'NNS': 1}, 'braille': {'NN': 1}, 'nearly': {'RB': 2}, 'training': {'NN': 1}, 'has': {'VBZ': 1}, 'carpentry': {'NN': 1}, 'year': {'NN': 1}, 'procedure': {'NN': 1}, 'PUBLISHED': {'CD': 1}, 'ATTERBURY': {'NN': 1}, 'graduated': {'VBD': 1}, 'coming': {'VBG': 1}, "'S": {'POS': 1}, '-LRB-': {'-LRB-': 11}, 'weekends': {'NNS': 1}, 'Veterans': {'NNP': 1}, 'men': {'NNS': 1}, 'Then': {'RB': 2}, 'teaches': {'VBZ': 1}, 'N6': {'NN': 1}, 'Creates': {'VBZ': 1}, '`': {'``': 1}, "'s": {'POS': 5, 'VBZ': 1}, 'There': {'EX': 1}, 'Murphy': {'NNP': 4}, 'OF': {'IN': 1}, 'Nebraska': {'NNP': 1}, 'knew': {'VBD': 1}, 'Naval': {'NNP': 1}, 'Puerto': {'NNP': 1}, 'they': {'PRP': 2}, 'each': {'DT': 2}, 'fleet': {'NN': 1}, 'dedicating': {'VBG': 1}, 'Col': {'NNP': 1}, 'way': {'NN': 1}, 'last': {'JJ': 2}, 'MEN': {'NNS': 1}, 'age': {'NN': 1}, 'chamber': {'NN': 1}, 'building': {'VBG': 3}, 'Job': {'NNP': 7}, 'rain': {'NN': 1}, 'crews': {'NNS': 1}, 'I': {'PRP': 3}, "'m": {'VBP': 2}, 'until': {'IN': 1}, '0112\xa0104141319': {'CD': 1}, 'lost': {'VBD': 1}, 'doctor': {'NN': 1}, 'Turn': {'VB': 1}, 'that': {'IN': 4, 'WDT': 1, 'DT': 1}, 'out': {'IN': 2, 'RP': 1}, 'declared': {'VBD': 1}, 'encourage': {'VBP': 1}, 'Day': {'NNP': 1}, 'Billy': {'NNP': 1}, 'opened': {'VBN': 1}, 'to': {'TO': 16}, 'took': {'VBD': 2}, 'issue': {'NN': 1}, 'separated': {'VBN': 1}, 'now': {'RB': 2}, 'History': {'NN': 1}, '-': {':': 1}, 'FOR': {'IN': 1}, 'banner': {'NN': 1}, 'did': {'VBD': 1}, 'SWORN': {'NNP': 1}, 'around': {'IN': 1}, 'nylon': {'NN': 1}, 'smelling': {'VBG': 1}, ',': {',': 27}, 'sign': {'NN': 1}, 'home': {'NN': 1}, 'underwater': {'JJ': 1}, 'recently': {'RB': 1}, 'Yeh': {'NNP': 1}, 'Results': {'NNS': 2}, 'talking': {'VBG': 2}, ';': {':': 1}, 'v': {'LS': 1}, 'longed': {'VBN': 1}, 'making': {'VBG': 1}, 'help': {'NN': 1}, 'was': {'VBD': 11}, 'educational': {'JJ': 1}, 'brother': {'NN': 1}, 'there': {'EX': 1}, 'found': {'VBD': 1}, 'mile': {'NN': 1}, 'Track': {'NNP': 2}, 'second': {'JJ': 2}, '2-BRA1LLE': {'JJ': 1}, 'Indiana': {'NNP': 1}, 'All-American': {'NNP': 1}, 'at': {'IN': 10}, '1': {'CD': 1}, 'through': {'IN': 1}, 'been': {'VBN': 1}, 'The': {'DT': 12}, 'Navy': {'NNP': 6}, 'fellow': {'JJ': 2}, 'Willie': {'NNP': 9}, 'Newman': {'NNP': 5}, 'IS': {'VBZ': 2}, 'snapshot': {'NN': 1}, 'over': {'IN': 4}, 'FIRST': {'NNP': 1}, 'can': {'MD': 2}, 'on': {'IN': 6, 'RB': 1}, 'saved': {'VBN': 1}, 'began': {'VBD': 3}, 'same': {'JJ': 1}, 'discover': {'VB': 1}, 'near': {'IN': 1}, 'education': {'NN': 1}, "'": {'POS': 2, "''": 1}, 'turned': {'VBD': 1}, 'heavy': {'JJ': 1}, 'member': {'NN': 1}, 'Dixon': {'NNP': 3}, 'rolled': {'VBD': 1}, 'Lincoln': {'NNP': 1}, 'live': {'VB': 1}, 'TRAIL': {'NN': 1}, 'eyes': {'NNS': 1}, '31': {'CD': 1}, 'Field': {'NNP': 1}, 'who': {'WP': 5}, 'completed': {'VBN': 1}, 'mothball': {'VB': 1}, 'Graduate': {'NNP': 1}, 'seven': {'CD': 1}, 'seventh': {'JJ': 1}, 'lifeguard': {'NN': 1}, 'me': {'PRP': 1}, '-RRB-': {'-RRB-': 11}, 'them': {'PRP': 1}, 'house': {'NN': 1}, 'raised': {'VBN': 1}, '500,000': {'CD': 1}, 'LEWISTON': {'NNP': 2}, 'squinted': {'VBD': 1}, 'by': {'IN': 7}, 'worked': {'VBD': 1}, 'spare': {'JJ': 1}, 'he': {'PRP': 13}, 'half-brothers': {'NNS': 1}, 'Cont': {'NNP': 1}, 'Vol.fo': {'NNP': 1}, 'D.C.': {'NNP': 1}, 'ago': {'IN': 1, 'RB': 1}, 'Championships': {'NNP': 1}, 'Braille': {'NNP': 3}, 'director': {'NN': 1}, 'will': {'MD': 1}, 'Ed': {'NNP': 1}, 'Now': {'RB': 1}, 'back': {'RB': 3}, 'WOMEN': {'NNS': 1}, 'THANKS': {'NNP': 1}, 'their': {'PRP$': 4}, 'pool': {'NN': 1}, 'Last': {'JJ': 1}, 'HISTORY': {'NN': 1, 'NNP': 1}, 'He': {'PRP': 3}, 'not': {'RB': 2}, 'streets': {'NNS': 1}, 'with': {'IN': 1}, 'from': {'IN': 6}, 'wilderness': {'NN': 1}, 'immediately': {'RB': 1}, 'paraded': {'VBD': 1}, 'To': {'TO': 1}, 'rough': {'JJ': 1}, '?': {'.': 1}, '20': {'CD': 1}, 'stepped': {'VBD': 1}, 'naval': {'JJ': 3}, 'gets': {'VBZ': 1}, 'give': {'VB': 1}, 'first': {'JJ': 3}, 'placed': {'VBN': 1}, 'INSIDE': {'IN': 1}, 'NEWMAN': {'NNP': 1}, 'LINCOLN': {'NNP': 1}, 'tongue': {'NN': 1}, 'life': {'NN': 4}, 'knowledge': {'NN': 1}, 'gasping': {'VBG': 1}, 'could': {'MD': 1}, 'nature': {'NN': 3}, 'Hi': {'UH': 1}, 'congratulations': {'NNS': 1}, 'sent': {'VBN': 1, 'VBD': 1}, 'That': {'DT': 1}, 'suggestion': {'NN': 1}, 'tried': {'VBD': 2}, 'October': {'NNP': 1}, 'respiration': {'NN': 1}, 'admit': {'VB': 1}, 'It': {'PRP': 2}, 'MADE': {'NNP': 1}, 'its': {'PRP$': 1}, 'which': {'WDT': 3}, 'creek': {'JJ': 1}, 'tree': {'NN': 2}, 'Another': {'DT': 1}, 'almost': {'RB': 1}, 'Marion': {'NNP': 5}, 'an': {'DT': 2}, 'brought': {'VBD': 1}, 'air': {'NN': 1}, 'equipment': {'NN': 1}, 'Working': {'VBG': 1}, 'emergency': {'NN': 1}, 'suggests': {'VBZ': 1}, 'natural': {'JJ': 1}, 'be': {'VB': 2}, 'attack': {'NN': 1}, 'into': {'IN': 1}, 'looked': {'VBD': 1}, 'COLLBRAN': {'NNP': 1}, '1967': {'CD': 2}, 'JOHN': {'NNP': 1}, 'NATION': {'NN': 1}, 'Twin': {'NNP': 3}, 'rings': {'NNS': 1}, 'enlist': {'VB': 1}, 'time': {'NN': 5}, 'were': {'VBD': 3}, 'stood': {'VBD': 1}, 'kept': {'VBD': 1}, 'By': {'IN': 2}, 'November': {'NNP': 1}, 'America': {'NNP': 2}, 'Trail-was': {'NNPS': 1}, 'AS': {'JJ': 1}, 'thousands': {'NNS': 1}, 'Meet': {'NNP': 1}, 'When': {'WRB': 1}, 'But': {'CC': 4}, 'Byt': {'NNP': 1}, 'embraced': {'VBD': 1}, 'River': {'NNP': 1}, 'between': {'IN': 1}, 'mouth-to-mouth': {'JJ': 1}, 'thinking': {'NN': 1}, 'observation': {'NN': 1}, 'Employment': {'NNP': 1}, 'intently': {'RB': 1}, 'Quick': {'NNP': 1}, 'fingers': {'NNS': 1}, 'BRAILLE': {'NNP': 1}, 'about': {'IN': 1}, 'joined': {'VBD': 2}, 'Bright': {'NNP': 1}, 'family': {'NN': 2}, 'see': {'VB': 3}, '3': {'CD': 1}, 'forest': {'NN': 2}, 'difference': {'NN': 1}, 'no': {'DT': 2}, 'AND': {'CC': 2}, "''": {"''": 9}, 'rope': {'NN': 1}, "n't": {'RB': 3}, 'Corps': {'NNP': 7}, 'Joining': {'VBG': 1}, 'kiss': {'NN': 1}, 'Blind': {'NNP': 2}, 'when': {'WRB': 3}, 'arranged': {'VBN': 1}, 'bran': {'NN': 1}, 'Action': {'NNP': 1}, 'day': {'NN': 2}, 'along': {'IN': 2}, 'beauties': {'NNS': 1}, '^': {'SYM': 2}, 'possible': {'JJ': 1}, 'filed': {'VBD': 1}, 'like': {'IN': 1}, 'officials': {'NNS': 1}, 'Time': {'NNP': 1}, 'blind': {'JJ': 6}, 'might': {'MD': 1}, 'other': {'JJ': 3}, 'of': {'IN': 23}, 'born': {'VBN': 1}, 'CORPS': {'VBZ': 1}, 'and': {'CC': 25}, 'visitors': {'NNS': 1}, 'stump': {'NN': 1}, 'Forest': {'NNP': 1}, 'Colorado': {'NNP': 5}, 'received': {'VBN': 1}, 'Wells': {'NNP': 1}, 'one': {'CD': 1}, 'studying': {'VBG': 1}, 'high': {'JJ': 1}, '£': {'$': 1}, '200': {'CD': 1}, '>': {'JJR': 2}, 'right': {'NN': 1, 'RB': 1}, 'Active': {'JJ': 1}, 'spent': {'VBD': 1}, 'free': {'JJ': 1}, 'later': {'RB': 1}, 'Deadline': {'NN': 1}, 'Announced': {'JJ': 1}, 'holding': {'VBG': 1}, 'Atterbury': {'NNP': 1}, 'bark': {'NN': 2}, 'month': {'NN': 3}, 'S': {'NN': 1}, 'went': {'VBD': 2}, 'officially': {'RB': 1}, 'leave': {'NN': 1}, 'Idaho': {'NNP': 2}, 'dropouts': {'NNS': 1}, 'Deaf': {'JJ': 1}, 'MAKES': {'VBZ': 1}, 'Governor': {'NNP': 1}, 'active': {'JJ': 1}, 'the': {'DT': 53}, 'Six': {'CD': 1}, 'never': {'RB': 1}, 'those': {'DT': 1}, 'First': {'NNP': 2}, 'only': {'RB': 1}}}, 'footer': None, 'calculatedLanguage': 'en'}, {'seq': '00000002', 'version': '1d39e9630d495a19d14764956a304e0f', 'tokenCount': 1491, 'lineCount': 262, 'emptyLineCount': 5, 'sentenceCount': 79, 'header': {'tokenCount': 7, 'lineCount': 2, 'emptyLineCount': 0, 'sentenceCount': 1, 'capAlphaSeq': 1, 'beginCharCount': {'2': 1, 'N': 1}, 'endCharCount': {'7': 1, 'N': 1}, 'tokenPosCount': {'CORPSMAN': {'NN': 1}, 'THE': {'DT': 1}, ',': {',': 1}, '1': {'CD': 1}, '2': {'CD': 1}, '1967': {'CD': 1}, 'November': {'NNP': 1}}}, 'body': {'tokenCount': 1484, 'lineCount': 260, 'emptyLineCount': 5, 'sentenceCount': 78, 'capAlphaSeq': 5, 'beginCharCount': {'E': 7, 'e': 4, 's': 18, 'n': 1, 'N': 4, 'j': 1, 'y': 2, 'T': 11, 't': 28, 'J': 7, 'f': 4, 'F': 2, 'A': 6, 'a': 18, 'm': 8, 'M': 4, 'I': 12, 'i': 4, '"': 1, 'G': 4, 'V': 2, 'L': 1, 'b': 9, 'g': 5, 'B': 4, 'l': 6, 'P': 3, 'p': 5, '2': 1, 'C': 10, 'H': 2, 'c': 7, 'W': 4, 'h': 5, '(': 2, 'r': 2, 'K': 1, 'w': 10, 'R': 6, 'k': 2, 'O': 4, 'D': 2, 'o': 8, 'S': 4, 'd': 4}, 'endCharCount': {'e': 32, 's': 25, 'n': 13, '.': 34, 'N': 3, 'y': 11, 't': 7, 'u': 1, 'f': 5, 'F': 2, 'A': 1, 'a': 2, 'm': 3, ')': 6, '"': 5, '-': 30, ',': 10, 'G': 1, '6': 2, 'L': 1, 'b': 2, 'g': 6, 'l': 2, '?': 1, '2': 1, 'h': 9, 'r': 8, 'w': 2, ':': 2, 'R': 1, 'O': 1, 'D': 1, 'o': 10, 'S': 2, 'd': 13}, 'tokenPosCount': {'terrible': {'JJ': 1}, 'lights': {'NNS': 1}, 'snow': {'NN': 1}, 'INTERVIEWER': {'NN': 1}, 'beneath': {'IN': 1}, 'At': {'IN': 1}, 'funny': {'JJ': 2}, 'rub': {'VB': 1}, 'routine': {'JJ': 1}, 'quality': {'NN': 1}, 'reporters': {'NNS': 1}, '18222': {'CD': 1}, 'One': {'CD': 1}, 'On': {'IN': 1}, 'seeking': {'VBG': 1}, 'Falls': {'NNP': 3}, 'ways': {'NNS': 1}, 'for': {'IN': 8}, 'WASHINGTON': {'NNP': 1}, 'Raymond': {'NNP': 1}, 'sturdy': {'JJ': 1}, '``': {'``': 7}, 'program': {'NN': 1}, 'find': {'VB': 1, 'VBP': 1}, 'business': {'NN': 1}, 'Benjamin': {'NNP': 1}, 'winner': {'NN': 1}, 'school': {'NN': 2}, 'art': {'NN': 1}, 'community': {'NN': 1}, 'officer': {'NN': 1}, 'further': {'JJ': 1}, 'feel': {'NN': 1, 'VBP': 1}, 'Henry': {'NNP': 1}, 'FLEXED': {'VBD': 1}, 'Arecibo': {'NNP': 1}, 'people': {'NNS': 6}, 'Huntington': {'NNP': 2}, 'CIRCLE': {'NNP': 1}, 'any': {'DT': 1}, 'city': {'NN': 1}, 'Beasley': {'NNP': 1}, '20036': {'CD': 3}, 'across': {'IN': 1}, 'years': {'NNS': 4}, 'young': {'JJ': 2}, 'CORPSMAN': {'NNP': 2}, 'huge': {'JJ': 1}, 'this': {'DT': 6}, 'Hyman': {'NNP': 1}, 'THIS': {'DT': 1}, 'in': {'IN': 21}, 'wives': {'NNS': 1}, 'Harold': {'NNP': 1}, 'have': {'VB': 3, 'VBP': 5}, 'your': {'PRP$': 2}, 'Paso': {'NNP': 2}, 'John': {'NNP': 1}, 'California': {'NNP': 1}, 'fights': {'VBZ': 1}, 'point': {'NN': 1}, 'are': {'VBP': 12}, 'SLY': {'NNP': 1}, 'is': {'VBZ': 13}, 'Barbara': {'NNP': 1}, 'How': {'WRB': 1}, 'knows': {'VBZ': 1}, 'too': {'RB': 4}, 'manage': {'VBP': 1}, 'graduate': {'NN': 1}, 'labor': {'NN': 1}, 'Circle': {'NNP': 2}, 'among': {'IN': 1}, 'Rico': {'NNP': 2}, 'built': {'VBD': 1}, 'Joe': {'NNP': 1}, 'makes': {'VBZ': 1}, 'Ray': {'NNP': 1}, 'everyone': {'NN': 1}, 'Hill': {'NNP': 1}, 'billboard': {'NN': 1}, 'fewer': {'JJR': 1}, 'said': {'VBD': 3}, 'try': {'VB': 1}, 'JOB': {'NNP': 2}, 'nobody': {'NN': 1}, 'Continued': {'VBN': 2}, 'America-is': {'NNPS': 1}, 'CHRISTOPHER': {'NNP': 1}, 'gathered': {'VBD': 1}, 'Washington': {'NNP': 3}, 'They': {'PRP': 1}, 'system': {'NN': 1}, 'Robert': {'NNP': 1}, 'Gregory': {'NNP': 2}, 'than': {'IN': 3}, 'union': {'NN': 1}, 'strikes': {'VBZ': 1}, 'Box': {'NNP': 1}, 'SEMI-MONTHLY': {'NN': 1}, 'McDONALD': {'NNP': 1}, 'want': {'VBP': 3}, 'vocational': {'JJ': 1}, 'P.O.': {'NNP': 1}, 'three': {'CD': 1}, 'walked': {'VBD': 1}, 'stories': {'NNS': 2}, 'youand': {'JJ': 1}, 'six-week': {'JJ': 1}, 'pals': {'NNS': 3}, 'William': {'NNP': 1}, 'EDITORIAL': {'NNP': 1}, 'ASSISTANT': {'NNP': 1}, '.': {'.': 74}, 'In': {'IN': 1}, '15': {'CD': 1}, 'but': {'CC': 2}, 'desires': {'NNS': 1}, 'sure': {'JJ': 1}, 'She': {'PRP': 1}, 'wrong': {'JJ': 1}, 'Timothy': {'NNP': 1}, 'best': {'JJS': 1}, 'President': {'NNP': 2}, 'ed': {'VBD': 1}, 'Corpsman': {'NN': 2, 'NNP': 7}, 'COMMUNITY': {'NNP': 1}, 'what': {'WP': 1}, 'would': {'MD': 6}, 'light-falling': {'JJ': 1}, 'Clark': {'NNP': 1}, 'JOIN': {'VB': 1}, 'pleasure': {'NN': 1}, 'Get': {'VB': 1}, 'opportunities': {'NNS': 1}, 'photographers': {'NNS': 1}, 'students': {'NNS': 3}, 'THE': {'DT': 6}, 'Quits': {'VBZ': 1}, 'if': {'IN': 1}, 'futures': {'NNS': 1}, 'center': {'NN': 6}, 'good': {'JJ': 4}, 'world': {'NN': 1}, 'lucky': {'JJ': 1}, 'My': {'PRP$': 1}, 'big': {'JJ': 1}, 'own': {'JJ': 2}, 'up': {'RP': 3}, 'Spanish-speaking': {'JJ': 2}, 'going': {'VBG': 4}, 'Spanish-American': {'JJ': 1}, 'population': {'NN': 1}, 'so': {'RB': 1}, 'clear': {'JJ': 1}, 'Why': {'WRB': 2}, 'our': {'PRP$': 1}, 'DUPONT': {'NNP': 1}, 'muscular': {'JJ': 1}, 'excellent': {'JJ': 1}, 'organize': {'VB': 1}, 'Jersey': {'NNP': 1}, 'WILLIAM': {'NNP': 1}, 'do': {'VB': 1}, 'all': {'PDT': 1, 'DT': 3}, 'DIRECTOR': {'NNP': 1, 'NN': 1}, '212': {'CD': 3}, 'stumbled': {'VBD': 1}, 'hand': {'NN': 1}, 'practically': {'RB': 1}, 'suggest': {'VBP': 1}, 'STAFF': {'NNP': 1}, 'had': {'VBD': 1}, 'Fred': {'NNP': 1}, 'recreation': {'NN': 1}, 'trail': {'NN': 4}, 'Texas': {'NNP': 1}, 'look': {'VB': 1, 'VBP': 1}, 'prepare': {'VB': 1}, 'cut': {'VBN': 2}, 'biologist': {'NN': 1}, 'A.': {'NNP': 1}, 'Utah': {'NNP': 1}, 'page': {'NN': 2}, 'every': {'DT': 2}, 'parents': {'NNS': 1}, 'Colhy': {'NNP': 1}, 'dead': {'JJ': 1}, 'articles': {'NNS': 2}, 'opportunity': {'NN': 3}, 'came': {'VBD': 3}, 'idea': {'NN': 2}, 'before': {'IN': 1}, 'Besides': {'IN': 1}, 'Great': {'NNP': 1}, 'discovering': {'VBG': 1}, 'Smith': {'NNP': 2}, 'interviewed': {'VBN': 1}, 'just': {'RB': 5}, 'saw': {'VBD': 1}, 'Girls': {'NNS': 1}, 'us': {'PRP': 1}, 'left': {'VBD': 1}, 'recruiting': {'NN': 1, 'VBG': 1}, 'understand': {'VBP': 1}, 'it': {'PRP': 7}, 'DuPont': {'NNP': 1}, 'Battle': {'NNP': 1}, 'Asked': {'VBN': 1}, 'brothers': {'NNS': 1}, 'sleep': {'VB': 1}, 'Grad'

In [11]:
counts1 = tokens_count(parsed1)
counts2 = tokens_count(parsed2)
print(counts1)
print(counts2)

Counter({'.': 410, 'the': 297, ',': 214, 'to': 174, 'a': 163, 'and': 160, 'in': 133, 'of': 133, 'is': 66, 'The': 63, "''": 63, '``': 61, 'I': 57, "'s": 56, 'that': 53, 'was': 50, 'for': 48, '-LRB-': 48, '-RRB-': 48, 'they': 46, 'Corpsmen': 39, 'are': 38, 'Job': 38, 'Corps': 38, 'it': 37, 'with': 35, 'be': 35, 'at': 34, 'you': 34, 'he': 33, 'as': 31, 'on': 31, 'by': 29, 'their': 28, 'have': 27, 'center': 26, 'Corpsman': 25, 'were': 25, 'out': 24, 'from': 24, 'do': 24, 'all': 23, 'an': 23, "n't": 22, 'this': 22, 'It': 20, 'not': 19, 'like': 19, ':': 19, 'we': 19, 'would': 18, 'up': 18, '?': 18, 'his': 17, '-': 17, 'time': 17, 'about': 17, 'one': 17, 'she': 17, 'They': 16, 'But': 16, 'should': 16, 'people': 15, 'In': 15, 'had': 15, 'two': 15, 'He': 15, 'other': 15, 'but': 14, 'been': 14, 'who': 14, 'them': 14, 'good': 14, 'just': 13, 'over': 13, 'when': 13, 'work': 13, 'THE': 12, 'has': 12, 'into': 12, 'Larry': 12, 'years': 11, 'help': 11, 'through': 11, 'because': 11, 'think': 11, 'get': 11, 'came': 10, 'Newman': 10, 'can': 10, "'": 10, 'will': 10, 'first': 10, 'blind': 10, 'community': 10, 'centers': 10, 'know': 10, 'go': 10, 'school': 9, 'trail': 9, 'Leon': 9, 'training': 9, 'Willie': 9, 'which': 9, 'see': 9, 'right': 9, 'month': 9, 'program': 9, 'Ottawa': 9, 'use': 9, 'game': 9, 'Corpswomen': 9, 'feel': 8, 'too': 8, 'what': 8, 'own': 8, 'so': 8, 'him': 8, 'A': 8, 'job': 8, 'now': 8, 'talking': 8, 'Navy': 8, 'little': 8, 'staff': 8, 'Coburn': 8, 'student': 8, 'your': 7, 'And': 7, 'men': 7, 'OF': 7, 'took': 7, 'there': 7, 'When': 7, 'no': 7, 'only': 7, 'Jersey': 7, 'these': 7, 'Iris': 7, 'also': 7, 'how': 7, 'after': 7, 'take': 7, 'lot': 7, 'her': 7, 'better': 7, 'more': 7, 'New': 7, 'fire': 7, 'set': 7, 'Ohio': 7, 'put': 7, 'Falls': 6, 'working': 6, 'said': 6, 'Washington': 6, 'thought': 6, 'each': 6, 'found': 6, 'began': 6, 'me': 6, 'ago': 6, 'life': 6, 'Twin': 6, 'day': 6, 'Colorado': 6, 'went': 6, 'Idaho': 6, 'any': 6, 'want': 6, 'if': 6, 'or': 6, 'service': 6, 'week': 6, 'long': 6, 'often': 6, 'even': 6, 'fight': 6, 'news': 6, 'where': 6, 'many': 6, 'some': 6, 'You': 6, 'keep': 6, 'town': 6, 'contest': 6, 'What': 6, 'Week': 6, 'sheriff': 6, 'Bridge': 6, 'court': 6, 'read': 5, 'find': 5, 'Rico': 5, 'three': 5, 'students': 5, 'every': 5, 'before': 5, 'Then': 5, 'There': 5, 'Puerto': 5, 'last': 5, 'did': 5, 'around': 5, 'director': 5, 'back': 5, 'pool': 5, 'To': 5, 'could': 5, 'October': 5, 'Marion': 5, 'River': 5, '3': 5, 'AND': 5, 'high': 5, 'leave': 5, 'never': 5, 'How': 5, 'than': 5, 'She': 5, 'going': 5, 'We': 5, 'man': 5, 'country': 5, 'Center': 5, 'team': 5, 'West': 5, 'may': 5, 'course': 5, 'made': 5, 'practice': 5, 'able': 5, 'Kilmer': 5, 'Harpers': 5, 'meet': 5, 'events': 5, 'children': 5, 'Newspaper': 5, 'called': 5, 'says': 5, 'JUDGE': 5, 'DEF': 5, 'One': 4, 'newspaper': 4, 'John': 4, 'California': 4, 'got': 4, 'system': 4, 'cut': 4, 'page': 4, 'idea': 4, 'left': 4, 'brothers': 4, 'movie': 4, 'year': 4, '`': 4, 'Murphy': 4, 'building': 4, 'FOR': 4, 'Track': 4, 'second': 4, '1': 4, 'live': 4, 'worked': 4, 'D.C.': 4, 'naval': 4, 'give': 4, 'nature': 4, 'sent': 4, 'its': 4, 'attack': 4, 'between': 4, 'might': 4, 'Atterbury': 4, 'At': 4, 'point': 4, 'among': 4, 'Get': 4, 'us': 4, 'understand': 4, 'volunteered': 4, 'Virginia': 4, 'become': 4, 'most': 4, 'VISTA': 4, 'my': 4, 'If': 4, 'new': 4, 'story': 4, 'taking': 4, 'members': 4, 'kind': 4, 'showing': 4, 'without': 4, 'off': 4, 'four': 4, 'far': 4, 'something': 4, 'friends': 4, 'wanted': 4, 'volunteer': 4, 'players': 4, 'must': 4, 'play': 4, 'shots': 4, 'much': 4, 'National': 4, 'show': 4, 'paper': 4, 'News': 4, 'shop': 4, 'gold': 4, 'Waterhole': 4, 'jobs': 4, 'X': 4, 'Y': 4, 'council': 4, 'executive': 4, 'Winners': 3, 'With': 3, 'professional': 3, 'needed': 3, 'built': 3, 'JOB': 3, 'lifesaving': 3, 'join': 3, 'President': 3, 'running': 3, 'recruiting': 3, 'became': 3, 'walk': 3, 'nearly': 3, 'ATTERBURY': 3, 'way': 3, "'m": 3, 'until': 3, 'educational': 3, 'Indiana': 3, 'member': 3, 'Dixon': 3, 'Braille': 3, 'Now': 3, 'gets': 3, 'That': 3, 'tried': 3, 'tree': 3, 'equipment': 3, '1967': 3, 'family': 3, 'forest': 3, 'along': 3, 'CORPS': 3, '>': 3, 'funny': 3, '20036': 3, 'young': 3, 'CORPSMAN': 3, 'makes': 3, 'Hill': 3, 'try': 3, 'Gregory': 3, 'pals': 3, '15': 3, 'photographers': 3, 'Why': 3, 'our': 3, '212': 3, 'opportunity': 3, 'Smith': 3, 'Editor': 3, 'proud': 3, 'attention': 3, 'Ellis': 3, 'EDITOR': 3, 'others': 3, 'problems': 3, 'pen': 3, 'bright': 3, "'ve": 3, 'need': 3, 'Kentucky': 3, 'KILMER': 3, 'James': 3, 'ones': 3, 'releases': 3, 'place': 3, 'special': 3, 'really': 3, 'concerned': 3, "'re": 3, 'TO': 3, '$': 3, 'important': 3, 'send': 3, 'Well': 3, "'ll": 3, 'field': 3, 'another': 3, 'weeks': 3, 'Molnar': 3, 'fires': 3, 'thing': 3, 'helping': 3, 'small': 3, 'helps': 3, 'make': 3, 'Miller': 3, 'fighting': 3, 'several': 3, 'let': 3, 'engine': 3, 'learn': 3, 'hard': 3, 'held': 3, 'track': 3, 'teams': 3, 'runs': 3, 'well': 3, 'stop': 3, 'hours': 3, 'ONE': 3, 'firsts': 3, 'improve': 3, 'ball': 3, 'position': 3, 'part': 3, "'d": 3, 'cue': 3, 'won': 3, 'McCoy': 3, 'photo': 3, 'explain': 3, '•': 3, 'talk': 3, 'nearby': 3, 'allowed': 3, 'Branson': 3, 'compete': 3, 'radio': 3, 'enter': 3, 'journalism': 3, 'Snake': 3, 'Marsing': 3, 'newsmen': 3, 'press': 3, 'extra': 3, 'great': 3, 'involved': 3, 'auto': 3, 'desert': 3, 'photography': 3, 'No.': 3, 'Q': 3, 'done': 3, 'judges': 3, 'stay': 3, 'congress': 3, 'Spanish': 3, 'government': 3, 'IN': 2, 'Brothers': 2, 'knowing': 2, 'officer': 2, 'For': 2, 'Harold': 2, 'graduate': 2, 'seen': 2, 'All': 2, 'nobody': 2, 'signs': 2, 'walked': 2, 'smooth': 2, 'future': 2, 'Walker': 2, 'minute': 2, 'NAVAL': 2, 'hearing': 2, 'crowd': 2, 'tests': 2, 'sworn': 2, 'Johnson': 2, 'braille': 2, 'PUBLISHED': 2, 'graduated': 2, "'S": 2, 'Nebraska': 2, 'Day': 2, 'issue': 2, 'sign': 2, 'home': 2, 'Results': 2, ';': 2, 'v': 2, 'making': 2, 'mile': 2, 'All-American': 2, 'fellow': 2, 'IS': 2, 'same': 2, 'discover': 2, 'education': 2, 'TRAIL': 2, 'Field': 2, 'seven': 2, 'raised': 2, 'LEWISTON': 2, 'spare': 2, 'Championships': 2, 'Last': 2, 'HISTORY': 2, 'streets': 2, 'rough': 2, 'NEWMAN': 2, 'knowledge': 2, 'Another': 2, 'emergency': 2, 'natural': 2, 'kept': 2, 'By': 2, 'America': 2, 'Meet': 2, 'BRAILLE': 2, 'joined': 2, 'Blind': 2, '^': 2, 'stump': 2, 'received': 2, 'studying': 2, 'spent': 2, 'free': 2, 'later': 2, 'bark': 2, 'Governor': 2, 'active': 2, 'First': 2, 'routine': 2, 'On': 2, 'ways': 2, 'Raymond': 2, 'sturdy': 2, 'Huntington': 2, 'city': 2, 'THIS': 2, 'Paso': 2, 'manage': 2, 'Circle': 2, 'everyone': 2, 'Continued': 2, 'stories': 2, 'wrong': 2, 'best': 2, 'opportunities': 2, 'world': 2, 'big': 2, 'Spanish-speaking': 2, 'DIRECTOR': 2, 'recreation': 2, 'Texas': 2, 'look': 2, 'A.': 2, 'articles': 2, 'office': 2, 'night': 2, 'bridge': 2, 'Pennsylvania': 2, 'certain': 2, 'Jones': 2, 'yourself': 2, 'These': 2, 'English': 2, 'understanding': 2, 'trained': 2, 'girls': 2, 'No': 2, 'bed': 2, 'passing': 2, 'Our': 2, 'Just': 2, 'PARK': 2, 'ruler': 2, 'nervous': 2, 'driver': 2, '17': 2, 'being': 2, 'asked': 2, 'shown': 2, 'poor': 2, 'BUREAU': 2, 'easy': 2, 'satisfied': 2, 'Some': 2, 'few': 2, 'Keystone': 2, 'Walter': 2, 'U.S.': 2, 'means': 2, 'Corpsmembers': 2, 'El': 2, 'under': 2, 'stationed': 2, 'themselves': 2, 'starting': 2, 'Corpswoman': 2, 'case': 2, 'As': 2, 'Nikkei': 2, 'does': 2, 'group': 2, 'poverty': 2, 'learning': 2, 'speak': 2, 'photos': 2, 'Building': 2, 'minor': 2, 'thinks': 2, 'Remember': 2, 'false': 2, 'name': 2, 'learned': 2, 'dropped': 2, 'fireman': 2, 'ARE': 2, 'stands': 2, 'broke': 2, 'AN': 2, 'ready': 2, 'Roger': 2, 'clean': 2, 'local': 2, 'bad': 2, 'tools': 2, 'Here': 2, 'prepared': 2, 'm': 2, 'gas': 2, 'Edward': 2, 'testing': 2, 'Bob': 2, 'Yes': 2, 'fact': 2, 'OTTAWA': 2, 'doing': 2, 'mind': 2, 'complete': 2, 'So': 2, 'Not': 2, 'large': 2, 'always': 2, 'close': 2, 'actual': 2, 'down': 2, 'winning': 2, 'shoot': 2, 'pocket': 2, 'Player': 2, 'performances': 2, 'tourney': 2, 'This': 2, 'spend': 2, 'style': 2, 'ran': 2, 'score': 2, '!': 2, 'biggest': 2, 'Branchville': 2, 'championship': 2, '10': 2, 'Liberty': 2, 'Anthony': 2, 'beginning': 2, 'comes': 2, 'moments': 2, 'national': 2, 'Valuable': 2, 'Most': 2, 'results': 2, 'Tillamook': 2, 'individual': 2, 'stamina': 2, 'dash': 2, 'again': 2, 'Mason': 2, 'both': 2, 'ten': 2, 'surprised': 2, 'five': 2, 'tough': 2, 'ahead': 2, 'longer': 2, 'playing': 2, 'pro': 2, 'baseball': 2, 'top': 2, 'former': 2, 'months': 2, 'BRECKINRIDGE': 2, 'usually': 2, 'Later': 2, 'puts': 2, 'touches': 2, 'mural': 2, 'Grande': 2, 'programs': 2, 'City': 2, 'Rio': 2, 'weekly': 2, 'Vannoy': 2, 'Student': 2, 'speed': 2, 'Oregon': 2, 'different': 2, 'problem': 2, 'Good': 2, 'REPORTER': 2, 'activities': 2, 'morale': 2, 'Mrs.': 2, 'INTERVIEWS': 2, 'popular': 2, 'color': 2, 'Start': 2, 'Done': 2, 'fall': 2, 'Head': 2, 'progress': 2, 'chance': 2, 'things': 2, 'curious': 2, 'bring': 2, 'builds': 2, 'publication': 2, 'skin': 2, 'days': 2, 'Groves': 2, 'TV': 2, 'critics': 2, 'used': 2, 'stage': 2, 'unto': 2, 'bandits': 2, 'darkroom': 2, 'tedious': 2, 'run': 2, 'buried': 2, 'apart': 2, 'Mr.': 2, 'told': 2, 'studio': 2, 'open': 2, 'comic': 2, 'army': 2, 'hour': 2, 'Automotive': 2, 'here': 2, 'repair': 2, 'naked': 2, 'chase': 2, 'then': 2, 'stations': 2, 'His': 2, 'tune-ups': 2, 'enough': 2, 'latest': 2, 'road': 2, 'assignment': 2, 'start': 2, 'western': 2, 'Each': 2, 'Defendant': 2, 'campaigns': 2, 'plan': 2, 'joining': 1, 'Flags': 1, 'trouble': 1, 'headline': 1, 'Lewiston': 1, 'Samuelson': 1, 'dot': 1, 'duty': 1, 'choking': 1, 'relative': 1, 'visits': 1, 'recognized': 1, 'Department': 1, 'tells': 1, 'count': 1, 'door': 1, 'bus': 1, 'MURPH-Harold': 1, 'dream': 1, 'feeling': 1, 'Trail': 1, 'stayed': 1, 'artificial': 1, '135': 1, 'TRAIL-Kenneth': 1, 'soon': 1, 'all-the': 1, 'worse': 1, 'watching': 1, 'shook': 1, 'hands': 1, 'weekend': 1, 'history': 1, 'meeting': 1, 'fir': 1, 'state': 1, 'nation': 1, 'HE': 1, 'Build': 1, 'dots': 1, 'career': 1, 'relatives': 1, 'annual': 1, 'glad': 1, 'flew': 1, 'Secretary': 1, 'Headquarters': 1, 'Walton': 1, '22': 1, 'dropout': 1, 'asthma': 1, 'trails': 1, '<': 1, 'served': 1, 'swallowed': 1, 'thanks': 1, 'alert': 1, 'Duty': 1, 'resuscitation': 1, 'miles': 1, '2-NEWMAN': 1, 'tropical': 1, 'onto': 1, 'birth': 1, 'announced': 1, 'patterns': 1, 'traveled': 1, '&': 1, 'Be': 1, 'trees': 1, 'Nation': 1, 'School': 1, 'ca': 1, 'failed': 1, 'spruce': 1, 'applied': 1, 'passed': 1, 'White': 1, 'Saved': 1, 'build': 1, 'stomach': 1, 'trail-called': 1, 'Buddies': 1, 'carpentry': 1, 'procedure': 1, 'coming': 1, 'weekends': 1, 'Veterans': 1, 'teaches': 1, 'N6': 1, 'Creates': 1, 'knew': 1, 'Naval': 1, 'fleet': 1, 'dedicating': 1, 'Col': 1, 'MEN': 1, 'age': 1, 'chamber': 1, 'rain': 1, 'crews': 1, '0112\xa0104141319': 1, 'lost': 1, 'doctor': 1, 'Turn': 1, 'declared': 1, 'encourage': 1, 'Billy': 1, 'opened': 1, 'separated': 1, 'History': 1, 'banner': 1, 'SWORN': 1, 'nylon': 1, 'smelling': 1, 'underwater': 1, 'recently': 1, 'Yeh': 1, 'longed': 1, 'brother': 1, '2-BRA1LLE': 1, 'snapshot': 1, 'FIRST': 1, 'saved': 1, 'near': 1, 'turned': 1, 'heavy': 1, 'rolled': 1, 'Lincoln': 1, 'eyes': 1, '31': 1, 'completed': 1, 'mothball': 1, 'Graduate': 1, 'seventh': 1, 'lifeguard': 1, 'house': 1, '500,000': 1, 'squinted': 1, 'half-brothers': 1, 'Cont': 1, 'Vol.fo': 1, 'Ed': 1, 'WOMEN': 1, 'THANKS': 1, 'wilderness': 1, 'immediately': 1, 'paraded': 1, '20': 1, 'stepped': 1, 'placed': 1, 'INSIDE': 1, 'LINCOLN': 1, 'tongue': 1, 'gasping': 1, 'Hi': 1, 'congratulations': 1, 'suggestion': 1, 'respiration': 1, 'admit': 1, 'MADE': 1, 'creek': 1, 'almost': 1, 'brought': 1, 'air': 1, 'Working': 1, 'suggests': 1, 'looked': 1, 'COLLBRAN': 1, 'JOHN': 1, 'NATION': 1, 'rings': 1, 'enlist': 1, 'stood': 1, 'November': 1, 'Trail-was': 1, 'AS': 1, 'thousands': 1, 'Byt': 1, 'embraced': 1, 'mouth-to-mouth': 1, 'thinking': 1, 'observation': 1, 'Employment': 1, 'intently': 1, 'Quick': 1, 'fingers': 1, 'Bright': 1, 'difference': 1, 'rope': 1, 'Joining': 1, 'kiss': 1, 'arranged': 1, 'bran': 1, 'Action': 1, 'beauties': 1, 'possible': 1, 'filed': 1, 'officials': 1, 'Time': 1, 'born': 1, 'visitors': 1, 'Forest': 1, 'Wells': 1, '£': 1, '200': 1, 'Active': 1, 'Deadline': 1, 'Announced': 1, 'holding': 1, 'S': 1, 'officially': 1, 'dropouts': 1, 'Deaf': 1, 'MAKES': 1, 'Six': 1, 'those': 1, 'terrible': 1, 'lights': 1, 'snow': 1, 'INTERVIEWER': 1, 'beneath': 1, 'rub': 1, 'quality': 1, 'reporters': 1, '18222': 1, 'seeking': 1, 'WASHINGTON': 1, 'business': 1, 'Benjamin': 1, 'winner': 1, 'art': 1, 'further': 1, 'Henry': 1, 'FLEXED': 1, 'Arecibo': 1, 'CIRCLE': 1, 'Beasley': 1, 'across': 1, 'huge': 1, 'Hyman': 1, 'wives': 1, 'fights': 1, 'SLY': 1, 'Barbara': 1, 'knows': 1, 'labor': 1, 'Joe': 1, 'Ray': 1, 'billboard': 1, 'fewer': 1, 'America-is': 1, 'CHRISTOPHER': 1, 'gathered': 1, 'Robert': 1, 'union': 1, 'strikes': 1, 'Box': 1, 'SEMI-MONTHLY': 1, 'McDONALD': 1, 'vocational': 1, 'P.O.': 1, 'youand': 1, 'six-week': 1, 'William': 1, 'EDITORIAL': 1, 'ASSISTANT': 1, 'desires': 1, 'sure': 1, 'Timothy': 1, 'ed': 1, 'COMMUNITY': 1, 'light-falling': 1, 'Clark': 1, 'JOIN': 1, 'pleasure': 1, 'Quits': 1, 'futures': 1, 'lucky': 1, 'My': 1, 'Spanish-American': 1, 'population': 1, 'clear': 1, 'DUPONT': 1, 'muscular': 1, 'excellent': 1, 'organize': 1, 'WILLIAM': 1, 'stumbled': 1, 'hand': 1, 'practically': 1, 'suggest': 1, 'STAFF': 1, 'Fred': 1, 'prepare': 1, 'biologist': 1, 'Utah': 1, 'parents': 1, 'Colhy': 1, 'dead': 1, 'Besides': 1, 'Great': 1, 'discovering': 1, 'interviewed': 1, 'saw': 1, 'Girls': 1, 'DuPont': 1, 'Battle': 1, 'Asked': 1, 'sleep': 1, 'Grad': 1, 'deserve': 1, 'mean': 1, 'clearly': 1, 'KELLY': 1, 'WHY': 1, 'regularly': 1, 'resident': 1, 'diploma': 1, 'Mack': 1, 'Reporter': 1, 'addressed': 1, 'walking': 1, 'Creek': 1, 'Becomes': 1, 'whose': 1, 'care': 1, 'Staff': 1, 'above': 1, 'letters': 1, 'looking': 1, 'Dupont': 1, 'FUNDS': 1, 'following': 1, 'PRINTING': 1, 'reply': 1, 'counselor': 1, 'television': 1, 'Winn': 1, 'enlistment': 1, 'Americans': 1, 'weightlifting': 1, 'grand': 1, 'L.': 1, 'McLaughlin': 1, 'SUPERVISION': 1, 'steered': 1, 'married': 1, 'Since': 1, 'cleared': 1, 'direct': 1, 'half': 1, 'Home': 1, 'RELATIONS': 1, 'Groomes': 1, 'MOSES': 1, 'Service': 1, 'declaring': 1, 'accidents': 1, 'encourages': 1, 'motivation': 1, 'water': 1, 'USE': 1, 'Opportunity': 1, 'advice': 1, 'SHE': 1, 'Volunteer': 1, 'VISTA-Volunteers': 1, 'EXPLAINS': 1, 'CASTLE': 1, 'drop-outs': 1, 'listen': 1, 'poetry': 1, 'Letters': 1, 'Photographers': 1, 'kinds': 1, 'fulfill': 1, 'Bryant': 1, 'TOM': 1, 'HUNTINGTON': 1, 'Middleton': 1, 'happy': 1, 'Guess': 1, '49017': 1, 'determination': 1, 'appears': 1, 'assisted': 1, 'Nazario': 1, 'studious': 1, 'boasted': 1, 'hope': 1, 'paid': 1, 'Reply': 1, 'Roaring': 1, 'Humor': 1, 'smell': 1, 'pick': 1, 'Haskell': 1, 'depressed': 1, 'Drums': 1, 'Gross': 1, 'WILLIAMS': 1, 'OEO': 1, 'sound': 1, 'Anyone': 1, 'D.O.': 1, 'Cunningham': 1, 'Northwest': 1, 'enlisted': 1, 'Jobs': 1, '42259': 1, 'supervision': 1, 'Vice': 1, 'Fuentes': 1, 'MUSCLES': 1, 'K-27': 1, 'ribbon': 1, 'giggling': 1, 'BUILDING': 1, 'counsel': 1, 'compromise': 1, 'Every': 1, 'Betty': 1, 'conference': 1, 'areas': 1, 'knock': 1, 'ad': 1, 'pose': 1, 'anyone': 1, 'Lewis': 1, 'album': 1, 'material': 1, 'REPLY': 1, 'Welcome': 1, 'God': 1, 'Cave': 1, 'DECIDED': 1, 'Grinning': 1, 'Mammoth': 1, 'cartoons': 1, 'welcome': 1, 'anything': 1, 'BY': 1, '97': 1, 'P.': 1, 'busy': 1, 'Onyx': 1, 'BUDGET': 1, 'decided': 1, 'UNDER': 1, 'Fork': 1, 'Robinson': 1, 'March': 1, 'Foresters': 1, 'pride': 1, 'MAY': 1, 'IRIS': 1, 'LAKE': 1, 'Custer': 1, 'Lorry': 1, 'closest': 1, 'Room': 1, 'Send': 1, 'discovery': 1, 'spots': 1, 'Thomas': 1, 'Blackwell': 1, 'noticing': 1, 'clerical': 1, 'dedicate': 1, 'mailed': 1, 'known': 1, 'grads': 1, 'awe': 1, 'tutor': 1, 'towards': 1, 'places': 1, 'Southwest': 1, 'write': 1, 'improving': 1, 'record': 1, 'Recruiting': 1, 'VALLEY': 1, 'Michigan': 1, 'period': 1, 'APPROVED': 1, 'LP': 1, 'worker': 1, 'PUBLICATION': 1, 'Glenn': 1, 'e': 1, 'ABLAZE': 1, 'Brigade': 1, 's': 1, 'services': 1, 'BUILDINGS': 1, 'companies': 1, 'houses': 1, 'abandoned': 1, 'real': 1, 'n': 1, 'Ron': 1, 'OXYGEN': 1, 'included': 1, 'heads': 1, 'explained': 1, 'FIRE-FIGHTING': 1, 'return': 1, 'flames': 1, 'awakened': 1, '40-hour': 1, 'hurriedly': 1, 'MASK': 1, 'blaze': 1, 'SET': 1, 'ABANDONED': 1, 'McClelland': 1, 'outside': 1, 'g.': 1, 'sometimes': 1, 'forest-fire': 1, 'Hughley': 1, 'Marvin': 1, 'arrive': 1, 'Huffman': 1, 'okay': 1, 'trade': 1, 'surprise': 1, 'enrolled': 1, 'pick-up': 1, 'nice': 1, 'Harry': 1, 'ring': 1, 'groups': 1, 'Clinton': 1, 'glow': 1, 'answers': 1, 'Edwin': 1, 'i': 1, 'sons': 1, 'daughters': 1, 'assembled': 1, 'well-disciplined': 1, 'steady': 1, '32': 1, 'practical': 1, 'believe': 1, 'discovered': 1, 'th': 1, 'truck': 1, 'Roedrick': 1, 'SUITS': 1, 'flagpole': 1, 'oil': 1, 'wants': 1, 'firemen': 1, 'Rhodes': 1, 'Port': 1, 'Theopolis': 1, 'note': 1, 'valuable': 1, 'Newsome': 1, 'CALLS': 1, 'vacant': 1, 'masks': 1, 'Ivan': 1, 'bell': 1, 'fought': 1, 'dressed': 1, 'Fire': 1, 'TRAINING': 1, 'OIL': 1, 'skills': 1, 'control': 1, 'property': 1, 'Protects': 1, 'alright': 1, 'DRILL': 1, 'neighboring': 1, 'protect': 1, 'extinguishers': 1, '...': 1, 'skill': 1, 'form': 1, 'converted': 1, 'morning': 1, 'FIRE': 1, 'drill': 1, 'PROTECTIVE': 1, 'O': 1, 'dorms': 1, 'From': 1, 'shrill': 1, 'o': 1, 'alarm': 1, 'Too': 1, 'eye': 1, 'Does': 1, 'FROM': 1, 'Sportmanship': 1, '12': 1, 'portion': 1, 'footballer': 1, 'Park': 1, 'LIBERTY': 1, 'discus': 1, 'once': 1, 'ho': 1, 'Practice': 1, 'require': 1, '57-inch': 1, 'squarely': 1, 'chess': 1, '100': 1, 'Sports': 1, 'relay': 1, 'ROBERTS': 1, 'using': 1, 'teacher': 1, 'PROS': 1, 'CENTER': 1, 'sparked': 1, 'Series': 1, 'Luther': 1, 'Baseball': 1, 'standard': 1, 'Capital': 1, 'Adams': 1, 'Card': 1, 'DAWSON': 1, 'sight': 1, 'BACKSTOP': 1, 'reporter': 1, 'remember': 1, 'disappointing': 1, 'Elmo': 1, 'blocks': 1, 'LARRY': 1, 'stroke': 1, 'fielder': 1, 'scored': 1, 'fills': 1, '13-4': 1, 'hit': 1, 'Inaugurates': 1, 'trial': 1, 'overcut': 1, 'TIPS': 1, '19-ounce': 1, 'dual': 1, 'LOSES': 1, 'comfortable': 1, 'seconds': 1, '10.9': 1, 'Tri-Center': 1, 'tape': 1, 'Red': 1, 'HARPERS': 1, 'softball': 1, 'GREAT': 1, 'concentration': 1, 'Finals': 1, 'fanned': 1, 'CHAMPS': 1, 'beaten': 1, 'Craig': 1, 'Top': 1, '12-6': 1, 'BRANCHVILLE': 1, 'Dan': 1, 'ANTHONY': 1, 'opposition': 1, 'beating': 1, 'Leading': 1, 'sports': 1, 'iced': 1, 'performing': 1, 'Brown': 1, 'quite': 1, 'finest': 1, 'tournament': 1, '10.7': 1, 'BUT': 1, 'provide': 1, 'CAPITAL': 1, 'season': 1, '21': 1, 'Lately': 1, 'DiMaggio': 1, 'avoid': 1, 'conscious': 1, 'named': 1, 'christened': 1, 'object': 1, 'shot': 1, 'match': 1, 'miss': 1, 'Saturday': 1, 'fifteen': 1, 'hurdles': 1, 'undefeated': 1, 'Mays': 1, 'Cispus': 1, 'sparkling': 1, 'TAGS': 1, 'discussed': 1, 'guidance': 1, 'Briefs': 1, 'hold': 1, 'jolted': 1, 'MASON': 1, 'drama': 1, 'qualifications': 1, 'Although': 1, 'nothing': 1, 'experience': 1, 'coach': 1, 'points': 1, 'added': 1, '12-7': 1, 'low': 1, 'Ware': 1, 'Find': 1, 'upsets': 1, '180': 1, 'player': 1, 'Sox': 1, 'CISPUS': 1, 'one-sided': 1, 'overcutting': 1, 'error': 1, 'Breckinridge': 1, 'wo': 1, 'hits': 1, 'Bill': 1, 'honors': 1, 'humbled': 1, 'Award': 1, 'mistakes': 1, 'Dallas': 1, 'Bobby': 1, 'FEET': 1, 'struggle': 1, 'naturally': 1, 'aiming': 1, 'while': 1, 'AWAY': 1, '880': 1, 'gave': 1, 'UP': 1, 'yard': 1, 'finesse': 1, 'Concentrate': 1, 'spot': 1, 'Do': 1, 'steam': 1, 'football': 1, 'Thompson': 1, 'thrills': 1, 'requires': 1, 'honored': 1, 'considered': 1, '82-42-39': 1, 'Musial': 1, 'racking': 1, 'competition': 1, 'Dwight': 1, 'ONYX': 1, 'paying': 1, 'TURTLE': 1, 'LUTHER': 1, '880-yard': 1, 'Vesuvius': 1, 'straight': 1, '220': 1, 'Being': 1, 'Harriers': 1, 'BOB': 1, 'Elliot': 1, 'mark': 1, 'sharpens': 1, 'develop': 1, 'losers': 1, 'Cadero': 1, 'preparation': 1, 'Win': 1, 'FERRY': 1, 'Al': 1, 'i

In [12]:
df1 = clean_df(counts1, stop_en)
df1.nlargest(10, 'count')

         word  count
170  Corpsmen     39
222       Job     38
449     Corps     38
102    center     26
93   Corpsman     25
448       n't     22
411      time     17
24     people     15
614      good     14
727      work     13

In [13]:
df2 = clean_df(counts2, stop_en)
df2.nlargest(10, 'count')

            word  count
98      Corpsmen     56
320        Corps     55
140          Job     48
66        center     36
585          n't     36
60      Corpsman     29
19        people     21
2219       Negro     21
65           THE     19
46    Washington     18

In [14]:
dict1 = df1.set_index('word')['count'].to_dict()
print(get_keywords(dict1))

(0, '0.009*"Corps" + 0.007*"Job" + 0.007*"Corpsmen" + 0.005*"center" + 0.004*"Corpsman" + 0.004*"n\'t" + 0.003*"time" + 0.003*"THE" + 0.003*"years" + 0.002*"Newman"', 1, '0.007*"Corpsman" + 0.007*"Corps" + 0.006*"Corpsmen" + 0.006*"Job" + 0.005*"center" + 0.004*"n\'t" + 0.004*"good" + 0.003*"people" + 0.003*"work" + 0.003*"time"', 2, '0.011*"Corpsmen" + 0.009*"Job" + 0.007*"center" + 0.007*"Corps" + 0.006*"n\'t" + 0.005*"Corpsman" + 0.004*"good" + 0.003*"work" + 0.003*"people" + 0.003*"time"', 3, '0.008*"Corpsmen" + 0.007*"Job" + 0.006*"Corps" + 0.004*"n\'t" + 0.004*"Corpsman" + 0.004*"time" + 0.004*"center" + 0.003*"people" + 0.003*"Larry" + 0.003*"good"', 4, '0.010*"Corps" + 0.009*"Job" + 0.008*"Corpsmen" + 0.006*"center" + 0.005*"Corpsman" + 0.005*"n\'t" + 0.004*"time" + 0.004*"people" + 0.003*"work" + 0.003*"Larry"')

In [15]:
dict2 = df2.set_index('word')['count'].to_dict()
print(get_keywords(dict2))

(0, '0.007*"Corps" + 0.007*"Corpsmen" + 0.006*"Job" + 0.005*"center" + 0.004*"Corpsman" + 0.004*"n\'t" + 0.004*"Negro" + 0.003*"man" + 0.003*"people" + 0.003*"THE"', 1, '0.008*"Corpsmen" + 0.007*"Corps" + 0.006*"n\'t" + 0.006*"Job" + 0.005*"Corpsman" + 0.005*"center" + 0.003*"Negro" + 0.003*"people" + 0.003*"man" + 0.003*"back"', 2, '0.009*"Corps" + 0.007*"Corpsmen" + 0.007*"Job" + 0.005*"center" + 0.005*"n\'t" + 0.004*"Corpsman" + 0.003*"program" + 0.003*"world" + 0.003*"home" + 0.003*"photo"', 3, '0.009*"Corpsmen" + 0.008*"Corps" + 0.007*"Job" + 0.006*"n\'t" + 0.005*"center" + 0.004*"Corpsman" + 0.003*"Negro" + 0.003*"people" + 0.003*"THE" + 0.003*"Washington"', 4, '0.009*"Corpsmen" + 0.008*"Job" + 0.007*"Corps" + 0.005*"center" + 0.004*"n\'t" + 0.004*"Corpsman" + 0.003*"people" + 0.003*"THE" + 0.003*"photo" + 0.003*"great"')

In [ ]:
# = for \
# + for :

print(retrieve_data('ucbk.ark+=28722=h2ws8hz0x'))

{'code': 404, 'message': 'Volume ucbk.ark:/28722/h2ws8hz0x not found'}